// frontend/src/pages/Home.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "../services/api";
import "./Home.css";

interface Course {
	id: number;
	name: string;
	description: string;
}

export default function Home() {
	const [courses, setCourses] = useState<Course[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState("");

	useEffect(() => {
		api.get("public/courses")
			.json<Course[]>()
			.then(setCourses)
			.catch(() => setError("Failed to load courses"))
			.finally(() => setLoading(false));
	}, []);

	if (loading) {
		return <div className="container">Loading courses...</div>;
	}

	if (error) {
		return <div className="container error-alert">{error}</div>;
	}

	return (
		<div className="container">
			<h1 className="home-title">AP History Courses</h1>
			<div className="course-grid">
				{courses.map((course) => (
					<Link to={`/courses/${course.id}`} key={course.id} className="course-card">
						<h2 className="course-name">{course.name}</h2>
						<p className="course-description">{course.description}</p>
					</Link>
				))}
				{courses.length === 0 && (
					<p className="text-secondary text-center" style={{ gridColumn: "1/-1" }}>
						No courses available yet.
					</p>
				)}
			</div>
		</div>
	);
}

// frontend-solid/src/pages/Home.tsx
import { A } from "@solidjs/router";
import { createResource, For, Show, type JSX } from "solid-js";
import { useEntity } from "../contexts/ServicesContext";
import styles from "./Home.module.css";

interface Course {
    id: number;
    name: string;
    description: string;
}

export default function Home(): JSX.Element {
    const coursesService = useEntity<Course>("public/courses");
    const [courses] = createResource(() => coursesService.list());

    return (
        <div class="container">
            <Show
                when={courses()}
                fallback={
                    <Show
                        when={!courses.error}
                        fallback={
                            <div class={styles.errorAlert}>
                                Failed to load courses
                            </div>
                        }
                    >
                        <div>Loading courses...</div>
                    </Show>
                }
            >
                <h1 class={styles.homeTitle}>AP History Courses</h1>
                <div class={styles.courseGrid}>
                    <For each={courses()}>
                        {(course) => (
                            <A
                                href={`/courses/${course.id}`}
                                class={styles.courseCard}
                            >
                                <h2 class={styles.courseName}>
                                    {course.name}
                                </h2>
                                <p class={styles.courseDescription}>
                                    {course.description}
                                </p>
                            </A>
                        )}
                    </For>
                    <Show when={courses()?.length === 0}>
                        <p
                            class="text-secondary text-center"
                            style={{ "grid-column": "1/-1" }}
                        >
                            No courses available yet.
                        </p>
                    </Show>
                </div>
            </Show>
        </div>
    );
}
