// frontend/src/pages/Login.tsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import './Login.css'

export default function Login() {
	const [email, setEmail] = useState('')
	const [password, setPassword] = useState('')
	const [error, setError] = useState('')
	const [loading, setLoading] = useState(false)
	const { login } = useAuth()
	const navigate = useNavigate()

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault()
		setError('')
		setLoading(true)
		try {
			await login(email, password)
			navigate('/')
		} catch (err: any) {
			setError(err.message || 'Invalid email or password')
		} finally {
			setLoading(false)
		}
	}

	return (
		<div className="auth-container">
			<div className="auth-card">
				<h2 className="auth-title">Login to AP History</h2>
				{error && <div className="error-alert">{error}</div>}
				<form onSubmit={handleSubmit}>
					<div className="form-group">
						<label htmlFor="email">Email</label>
						<input
							type="email"
							id="email"
							className="form-control"
							value={email}
							onChange={(e) => setEmail(e.target.value)}
							required
						/>
					</div>
					<div className="form-group">
						<label htmlFor="password">Password</label>
						<input
							type="password"
							id="password"
							className="form-control"
							value={password}
							onChange={(e) => setPassword(e.target.value)}
							required
						/>
					</div>
					<button type="submit" className="btn btn-primary auth-submit" disabled={loading}>
						{loading ? 'Loading...' : 'Login'}
					</button>
				</form>
				<p className="auth-footer">
					Don't have an account? <Link to="/register" className="auth-link">Register</Link>
				</p>
			</div>
		</div>
	)
}

// frontend-solid/src/pages/Login.tsx
import { A, useNavigate } from "@solidjs/router";
import { createSignal, Show, type JSX } from "solid-js";
import { useAuthContext } from "../contexts/AuthContext";
import styles from "./Login.module.css";

export default function Login(): JSX.Element {
    const [email, setEmail] = createSignal("");
    const [password, setPassword] = createSignal("");
    const [error, setError] = createSignal("");
    const [loading, setLoading] = createSignal(false);
    const { login } = useAuthContext();
    const navigate = useNavigate();

    const handleSubmit = async (e: SubmitEvent): Promise<void> => {
        e.preventDefault();
        setError("");
        setLoading(true);
        try {
            await login(email(), password());
            navigate("/");
        } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            setError(message || "Invalid email or password");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div class={styles.authContainer}>
            <div class={styles.authCard}>
                <h2 class={styles.authTitle}>Login to AP History</h2>
                <Show when={error()}>
                    <div class={styles.errorAlert}>{error()}</div>
                </Show>
                <form onSubmit={handleSubmit}>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input
                            type="email"
                            id="email"
                            class="form-control"
                            value={email()}
                            onInput={(e) => setEmail(e.currentTarget.value)}
                            required
                        />
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input
                            type="password"
                            id="password"
                            class="form-control"
                            value={password()}
                            onInput={(e) =>
                                setPassword(e.currentTarget.value)
                            }
                            required
                        />
                    </div>
                    <button
                        type="submit"
                        class={`btn btn-primary ${styles.authSubmit}`}
                        disabled={loading()}
                    >
                        {loading() ? "Loading..." : "Login"}
                    </button>
                </form>
                <p class={styles.authFooter}>
                    Don't have an account?{" "}
                    <A href="/register" class={styles.authLink}>
                        Register
                    </A>
                </p>
            </div>
        </div>
    );
}
